export const AVAILABLE_SONGS = [
  {
    file: '0.mp3',
    name: 'Nebula Drift',
    artist: 'Aurora Vale',
    color: '#1F2937',
    image: '1.png',
  },
  {
    file: '1.mp3',
    name: 'Midnight Highway',
    artist: 'James Bell',
    color: '#D32F2F',
    image: '2.png',
  },
  {
    file: '2.mp3',
    name: 'Violet Haze',
    artist: 'Indigo Flux',
    color: '#6A1B9A',
    image: '3.png',
  },
  {
    file: '3.mp3',
    name: 'Golden Hour',
    artist: 'AnotherDay',
    color: '#FFB300',
    image: '4.png',
  },
  {
    file: '4.mp3',
    name: 'Paper Lanterns',
    artist: 'Marcus Wynn',
    color: '#90A4AE',
    image: '5.png',
  },
  {
    file: '5.mp3',
    name: 'Ashes & Echoes',
    artist: 'BadBadMeow',
    color: '#E64A19',
    image: '6.png',
  },
  {
    file: '6.mp3',
    name: 'Ocean Pulse',
    artist: 'Ocean Echo',
    color: '#0277BD',
    image: '7.png',
  },
  {
    file: '7.mp3',
    name: 'Echoes of You',
    artist: 'Echo Roads',
    color: '#0288D1',
    image: '8.jpg',
  },
  {
    file: '8.mp3',
    name: 'Radiant Bloom',
    artist: 'Lumen',
    color: '#F06292',
    image: '9.jpg',
  },
  {
    file: '9.mp3',
    name: 'Silent Compass',
    artist: 'Northbound',
    color: '#1565C0',
    image: '10.jpg',
  },
  {
    file: '10.mp3',
    name: 'Crimson Skies',
    artist: 'Scarlet Drift',
    color: '#C62828',
    image: '11.jpg',
  },
  {
    file: '11.mp3',
    name: 'Last Light',
    artist: 'Nocturne',
    color: '#37474F',
    image: '12.jpg',
  }
] as const;
